apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: test-app
  namespace: argocd

spec:
  source:
    repoURL: https://github.com/YOUR_USERNAME/tmtd-gitops.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
